config/routes.rb
Rails.application.routes.draw do

  root 'data_base#index'

  resources :artists
  resources :songs

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
  end

#An empty post form
  def new
    @artist = Artist.new
  end

  def create
    if @artist = Artist.create(artist_params)
       redirect_to root_path
     else
       render :new
     end
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])

    if @artist.update(artist_params)
      redirect_to @artist
    else
      render :edit
    end
  end

def destroy
  @artist = Artist.find(params[:id])
  if @artist.destroy
  redirect_to root_path
  else
  redirect_to @artist
  end
end

  private

  def post_params
    params.require(:artist).permit(:name, :birth_date, :country, :picture, :plot)
  end
end

app/controllers/data_base_controller.rb
class DataBaseController < ApplicationController
  def index
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = Song.all
  end

#An empty post form
  def new
    @song = Song.new
  end

  def create
    if @song = Song.create(song_params)
       redirect_to root_path
     else
       render :new
     end
  end

  def show
    @song = Song.find(params[:id])
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])

    if @song.update(song_params)
      redirect_to @song
    else
      render :edit
    end
  end

def destroy
  @song = Song.find(params[:id])
  if @song.destroy
  redirect_to root_path
  else
  redirect_to @song
  end
end

  private

  def post_params
    params.require(:song).permit(:title, :plot, :picture, :realease_date, :duration)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_artists.html.erb
<div class="col col s12 m6 l4">
  <article class="card-panel hoverable">
    <p><%= artist.image %></p>
      <h1><%= link_to artist.model, artist %></h1>
    <p><%= artist.description %></p>

  </article>
</div>

app/views/artists/index.html.erb
<div class="row">
<%= render @artists %>


</div>
<br />
<span class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons"><%= link_to "+", new_artist_path %></i></span>

app/views/artists/new.html.erb
<div class="">

<div class="headers">
<h1>ARTISTS</h1>
</div>

<div class="users_block">
<%= form_for(@artist) do |f| %>
<div>
  <p><%= f.label :name %></p>
  <%= f.text_field :name %>
</div>

<div>
  <p><%= f.label :birth_date %></p>
  <%= f.text_field :birth_date %>
</div>

<h5>Just the best Music</h5>

<div>
  <%= f.submit "Save Artist" %>
</div>

<p><%= link_to "Find your Artists", :class => "btn btn-primary btn-lg orange darken-1" %>

<% end %>
</div>
</div>

app/views/data_base/index.html.erb
<div class="jumbotron homepage-block">

<div class="titles">
  <h1>Global Artist/Songs Data</h1>
  <p>Your daily update of the best songs</p>

  <p><%= link_to "Artist", new_artist_path, :class => "btn btn-primary btn-lg green darken-1" %> <%= link_to "Songs", new_song_path, :class => "btn btn-primary btn-lg  green darken-1" %></p>
</div>

</div>

<div class="concert">
<%= image_tag "http://www.busestoconcerts.com/communities/8/004/008/554/698//images/4621827369.jpg" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>

<body class="<%= content_for?(:body_class) ? yield(:body_class) : "home" %>">
  <nav class="navbar navbar-default">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/"></a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav navbar-right">
    <li role="presentation"><a href="#">Messages <span class="badge">3</span></a></li>
      <li><a href="#">Sign up</a></li>

    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>
  <div class="container">

  <%= yield %>
</div>
</body>
</html>

app/views/songs/_songs.html.erb
<div class="col col s12 m6 l4">
  <article class="card-panel hoverable">
    <p><%= song.image %></p>
      <h1><%= link_to song.model, song %></h1>
    <p><%= song.description %></p>

  </article>
</div>

app/views/songs/index.html.erb
<div class="row">
<%= render @songs %>


</div>
<br />
<span class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons"><%= link_to "+", new_song_path %></i></span>

app/views/songs/new.html.erb
<div class="">

<div class="headers">
<h1>SONGS</h1>
</div>

<div class="users_block">
<%= form_for(@song) do |f| %>
<div>
  <p><%= f.label :title %></p>
  <%= f.text_field :title %>
</div>

<div>
  <p><%= f.label :duration %></p>
  <%= f.text_field :duration %>
</div>

<h5>Just the best Songs</h5>

<div>
  <%= f.submit "Save Song" %>
</div>

<p><%= link_to "Find your Songs", :class => "btn btn-primary btn-lg orange darken-1" %>

<% end %>
</div>
</div>